// COUPONS
export const COUPONS_REQUEST = 'COUPONS_REQUEST';
export const COUPONS_SUCCESS = 'COUPONS_SUCCESS';
export const COUPONS_FAIL = 'COUPONS_FAIL';

// FEATURED_STORE
export const FEATURED_STORE_REQUEST = 'FEATURED_STORE_REQUEST';
export const FEATURED_STORE_SUCCESS = 'FEATURED_STORE_SUCCESS';
export const FEATURED_STORE_FAIL = 'FEATURED_STORE_FAIL';

// TOP_CATEGORIES
export const TOP_CATEGORIES_REQUEST = 'TOP_CATEGORIES_REQUEST';
export const TOP_CATEGORIES_SUCCESS = 'TOP_CATEGORIES_SUCCESS';
export const TOP_CATEGORIES_FAIL = 'TOP_CATEGORIES_FAIL';

// CATEGORY_TITLE
export const CATEGORY_TITLE_REQUEST = 'CATEGORY_TITLE_REQUEST';
export const CATEGORY_TITLE_SUCCESS = 'CATEGORY_TITLE_SUCCESS';
export const CATEGORY_TITLE_FAIL = 'CATEGORY_TITLE_FAIL';

// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// COMMMON
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';